name: CI

on:
    - pull_request

jobs:
    lint:
        name: Code formatting & linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'
                  cache-dependency-path: pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting with Prettier
              run: pnpm format:check

            - name: Lint with ESLint
              run: pnpm lint:check

            - name: Check Typescript
              run: |
                  pnpm typecheck

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'
                  cache-dependency-path: pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting with Prettier
              run: pnpm test
